codecrumb/crumbs/routes.py
import json
import os
import secrets
import re

from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    safe_join,
    send_file,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user

from codecrumb import bcrypt, db
from codecrumb.crumbs.export import receive_export, handle_zip_file
from codecrumb.crumbs.utils import (
    anon_response,
    create_new_anonymous_crumb,
    create_new_crumb,
    json_response,
    save_crumb,
    save_pseudo,
)
from codecrumb.model import Anonymous_Crumbs, Crumbs, User
from codecrumb.oauth.forms import Search

set_crumb = Blueprint("set_crumb", __name__)


@set_crumb.route("/dashboard/crumbs", methods=["GET", "POST"])
@login_required
def crumbs():
    search = Search()
    
    title = "Your Crumbs"
    page = request.args.get("page", 1, int)
    crumb = (
        Crumbs.query.filter_by(userId=current_user.id)
        .order_by(Crumbs.date_created.desc())
        .paginate(page=page, per_page=6)
    )

    imageFile = url_for("static", filename="profile-images/" + current_user.image)
    if search.validate_on_submit():
        name = search.byname.data
        match = re.match(f"{name}*", name)
        print(match)
        crumbs = (
            Crumbs.query.filter_by(userId=current_user.id)
            .order_by(Crumbs.date_created.desc())
            .paginate(page=page, per_page=6)
        )

        for crumb in crumbs.items:
            if crumb.crumbName == name:
                return render_template(
                    "crumb.html",
                    title=f"Search - {name}",
                    image=imageFile,
                    crumbs=crumb,
                    json=json,
                    json_response=json_response,
                    search=search
                )
        # return redirect(url_for("main.editor"))
    return render_template(
        "crumb.html",
        title=title,
        image=imageFile,
        crumbs=crumb,
        json=json,
        json_response=json_response,
        search=search
    )



@set_crumb.route("/user/dashboard/crumbs/delete", methods=["GET", "POST"])
@login_required
def delete_crumb():

    if request.method == "GET":
        abort(403)
    else:
        req = request.get_json()
        del_data = req.get("id")
        crumb = Crumbs.query.filter_by(id=int(del_data)).first_or_404()
        user = User.query.get_or_404(crumb.userId)
        db.session.delete(crumb)
        db.session.commit()
        return make_response(jsonify(req), 200)
        # return redirect(url_for('crumbs'))


@set_crumb.route("/crumbs/get", methods=["GET", "POST"])
def code():

    if request.method == "GET":
        abort(403)

    if current_user.is_authenticated:
        response = request.get_json()
        path = response.get("path")
        crumb = Crumbs.query.filter_by(url=path).first_or_404()
        user = User.query.get_or_404(crumb.userId)
        if crumb:
            save_crumb(response, crumb, user, True)
            return make_response(jsonify({"repsonse": "request successful"}), 200)

    else:
        return make_response(jsonify({"repsonse": "unsuccessful"}), 400)


@set_crumb.route("/crumbs/new", methods=["GET", "POST"])
def save():
    url = secrets.token_urlsafe(6)
    if current_user.is_authenticated:
        crumbs = Crumbs(url=url, author=current_user)

        db.session.add(crumbs)
        db.session.commit()
        return redirect(
            url_for("set_crumb.codecrumb", author=current_user.username, url=url)
        )

    elif request.method == "GET":
        abort(403)


@set_crumb.route("/<author>/crumb/<url>", methods=["GET", "POST"])
def codecrumb(author, url):
    crumb = Crumbs.query.filter_by(url=url).first_or_404()
    user = User.query.filter_by(username=author).first_or_404()

    if crumb.userId != user.id:
        abort(404)

    if current_user.is_authenticated:
        imageFile = url_for("static", filename="profile-images/" + current_user.image)
        c_id = crumb.userId == current_user.id
        json_res = json_response(crumb, c_id)
        code = json.dumps(json_res)
        is_author = crumb.author.id == current_user.id
        title = json_res.get("title").get("name") if json_res.get("title").get("name") != "Unnamed Crumb" else "A Crumb"
        return render_template(
            "editor-v01.html",
            user=crumb,
            crumb=code,
            title=f"{title} by {author.capitalize()}",
            image=imageFile,
            is_author=is_author,
            snippets=user.snippet,
        )
    else:
        c_id = False
        is_author = False
        json_res = json_response(crumb, c_id)
        code = json.dumps(json_res)
        title = json_res.get("title").get("name") if json_res.get("title").get("name") != "Unnamed Crumb" else "A Crumb"
        return render_template(
            "editor-v01.html",
            user=crumb,
            crumb=code,
            title=f"{title} by {author.capitalize()}",
            is_author=is_author,
        )

@set_crumb.route("/<author>/crumb/<url>/<ext>", methods=["GET", "POST"])
def get_file(author, url, ext):
    crumb = Crumbs.query.filter_by(url=url).first_or_404()
    user = User.query.filter_by(username=author).first_or_404()

    if crumb.userId != user.id:
        abort(404)
    if request.method == 'POST':
        abort(400)


    if current_user.is_authenticated:
        if ext.lower() != 'css' and ext.lower() != 'js':
           
            return 'Code extension not supported.'
        elif ext.lower() == 'css':
            code = json_response(crumb, True)
            
            return code.get("codes").get("css")
        elif ext.lower() == 'js':
            code = json_response(crumb, True)
           
            return code.get("codes").get("js")



@set_crumb.route("/crumbs/fork", methods=["GET", "POST"])
def get_forked():
    if request.method == "GET":
        abort(403)

    if not current_user.is_authenticated:
        return make_response(jsonify({"Request Timeout": "Unsuccessful"}), 402)

    res = request.get_json()
    print(res)
    url = res.get("path")
    # author = res.get("author")
    # query db
    forked_crumb = Crumbs.query.filter_by(url=url).first_or_404()
    req = json_response(forked_crumb, False)
    new_url = secrets.token_urlsafe(6)
    new_crumb = Crumbs(url=new_url, author=current_user)
    db.session.add(new_crumb)
    db.session.commit()

    save_crumb(req, new_crumb, current_user, False)
    send_url = {"path": current_user.username + "/crumb/" + new_url}
    return make_response(jsonify(send_url), 200)


@set_crumb.route("/crumbs/save", methods=["GET", "POST"])
def get_saved():
    if request.method == "GET":
        abort(403)

    if not current_user.is_authenticated:
        return make_response(jsonify({"Request Timeout": "Unable to save"}), 403)

    res = request.get_json()

    # query db

    new_url = secrets.token_urlsafe(6)
    create_new_crumb(res, new_url)

    send_url = {"path": current_user.username + "/crumb/" + new_url}
    return make_response(jsonify(send_url), 200)


@set_crumb.route("/anon/crumbs", methods=["GET", "POST"])
def anonymous_crumb():
    if request.method == "GET":
        abort(403)

    res = request.get_json()

    new_url = secrets.token_urlsafe(6)

    create_new_anonymous_crumb(res, new_url)
    send_url = {"path": "anon/crumbs/" + new_url}
    return make_response(jsonify(send_url), 200)


@set_crumb.route("/anon/crumbs/<url>", methods=["GET", "POST"])
def get_anon_crumb(url):
    user = Anonymous_Crumbs.query.filter_by(url=url).first_or_404()

    if current_user.is_authenticated:
        imageFile = url_for("static", filename="profile-images/" + current_user.image)

        is_author = False
        code = json.dumps(anon_response(user))
        return render_template(
            "editor-v01.html",
            user=user,
            crumb=code,
            title="Anonymous Crumb",
            image=imageFile,
            is_author=is_author,
        )
    else:

        is_author = False
        code = json.dumps(anon_response(user))
        return render_template(
            "editor-v01.html",
            user=user,
            crumb=code,
            title="Anonymous Crumb",
            is_author=is_author,
        )


@set_crumb.route("/anon/crumbs/get", methods=["GET", "POST"])
def fork_anonymous_crumb():

    if request.method == "GET":
        abort(403)

    if not current_user.is_authenticated:
        return make_response(jsonify({"Request Timeout": "Unsuccessful"}), 402)

    res = request.get_json()
    print(res)
    url = res.get("path")
    # author = res.get("author")
    # query db
    forked_crumb = Anonymous_Crumbs.query.filter_by(url=url).first_or_404()
    req = anon_response(forked_crumb)
    new_url = secrets.token_urlsafe(6)
    new_crumb = Crumbs(url=new_url, author=current_user)
    db.session.add(new_crumb)
    db.session.commit()

    save_crumb(req, new_crumb, current_user, False)
    send_url = {"path": current_user.username + "/crumb/" + new_url}
    return make_response(jsonify(send_url), 200)


@set_crumb.route("/user/crumbs/snippets", methods=["GET", "POST"])
def snippets():
    if request.method == "GET":
        abort(403)

    res = request.get_json()

    snippet = res.get("snippet")
    user = User.query.get(current_user.id)

    user.snippet = snippet
    db.session.commit()

    return make_response(jsonify({"snippet": snippet}))



codecrumb/oauth/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from codecrumb import bcrypt, db
from codecrumb.model import Crumbs, User
from codecrumb.oauth.forms import (
    LoginForm,
    RegistrationForm,
    UpdateAccountForm,
    UpdatePasswordForm,
    deleteForm,
)
from codecrumb.oauth.utils import save_picture

oauth = Blueprint("oauth", __name__)


@oauth.route("/user/register", methods=["GET", "POST"])
def register():

    if current_user.is_authenticated:
        return redirect(url_for("main.editor"))
    title = "Sign Up"
    register = RegistrationForm()

    if register.validate_on_submit():
        hashed = bcrypt.generate_password_hash(register.password.data).decode("utf-8")
        email = register.email.data.lower()
        username = register.username.data.lower()
        newUser = User(username=username, email=email, password=hashed)
        db.session.add(newUser)
        db.session.commit()
        flash("Your account has been created Successfully.")
        flash("please sign in to continue.")
        return redirect(url_for("oauth.login"))

    return render_template("register.html", register=register, title=title)


@oauth.route("/user/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        return redirect(url_for("main.editor"))
    title = "Sign In"

    login = LoginForm()

    if request.method == "POST":
        if login.validate_on_submit():
            # these conditional tries to log a user in.
            # using either their email or username.
            loginEmail = login.username.data.lower()
            loginUsername = login.username.data.lower()
            userEmail = User.query.filter_by(email=loginEmail).first()
            userName = User.query.filter_by(username=loginUsername).first()

            if userEmail and bcrypt.check_password_hash(
                userEmail.password, login.password.data
            ):
                login_user(userEmail, remember=True)
                nextPage = request.args.get("next")
                return (
                    redirect(nextPage) if nextPage else redirect(url_for("main.editor"))
                )
            elif userName and bcrypt.check_password_hash(
                userName.password, login.password.data
            ):
                login_user(userName, remember=True)
                nextPage = request.args.get("next")
                return (
                    redirect(nextPage) if nextPage else redirect(url_for("main.editor"))
                )
            else:
                flash("Login unsuccessful!")
                flash("Please check the username or password")

    # if current_user.is_authenticated:
    #     return redirect(url_for('editor'))
    return render_template("login.html", login=login, title=title)


@oauth.route("/user/logout")
def logout():
    logout_user()
    return redirect(url_for("main.editor"))


@oauth.route("/user/account/dashboard", methods=["GET", "POST"])
@login_required
def account():
    if current_user.is_authenticated:
        title = "Dashboard"
        crumbSaved = Crumbs.query.filter_by(userId=current_user.id).count()
        personal = UpdateAccountForm()
        userPassword = UpdatePasswordForm()
        deletePassword = deleteForm()
        if personal.validate_on_submit():
            if personal.picture.data:
                newPicture = save_picture(personal.picture.data)
                current_user.image = newPicture

            if personal.firstname.data:
                current_user.firstname = personal.firstname.data

            if personal.lastname.data:
                current_user.lastname = personal.lastname.data

            if personal.location.data:
                current_user.location = personal.location.data

            if personal.github.data:
                current_user.github = personal.github.data

            current_user.username = personal.username.data.lower()
            current_user.email = personal.email.data.lower()
            db.session.commit()
            flash("Your profile has been updated succesfully")
            return redirect(url_for("oauth.account"))
        elif request.method == "GET":
            personal.username.data = current_user.username
            personal.email.data = current_user.email
            personal.lastname.data = current_user.lastname
            personal.firstname.data = current_user.firstname
            personal.location.data = current_user.location
            personal.github.data = current_user.github

        if userPassword.validate_on_submit():
            if (
                userPassword.password.data
                and userPassword.newPassword.data
                and userPassword.confirmNewPassword.data
            ):
                current_user.password = bcrypt.generate_password_hash(
                    userPassword.newPassword.data
                ).decode("utf-8")

                db.session.commit()
                flash("Your Profile has been updated succesfully")
                return redirect(url_for("oauth.account"))

        if deletePassword.validate_on_submit():
            user = User.query.get(current_user.id)
            if bcrypt.check_password_hash(user.password, deletePassword.pass_w.data):

                crumbs = Crumbs.query.filter_by(userId=user.id).all()

                if crumbs:
                    db.session.delete(user)
                    for i in crumbs:
                        db.session.delete(i)

                    db.session.commit()
                    # flash("Account deleted")
                    return redirect(url_for("main.editor"))
                else:
                    db.session.delete(user)
                    db.session.commit()
                    # flash("Account deleted")
                    return redirect(url_for("main.editor"))

        imageFile = url_for("static", filename="profile-images/" + current_user.image)
        return render_template(
            "account.html",
            title=title,
            personal=personal,
            image=imageFile,
            userPassword=userPassword,
            crumbSaved=crumbSaved,
            deletePassword=deletePassword,
            snippets=current_user.snippet,
        )

codecrumb/templates/crumb.html
{% extends 'layout.html' %} {% block meta %}
<link rel="stylesheet" href="{{url_for('static', filename='css/crumb.css')}}" />
{% endblock %}

<body>
  {% block body %}  <div class="header">
      <div class="logo">
        <a href="{{ url_for('main.editor') }}">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 72 72"><defs><style>.cls-1{stroke: none;}.cls-2{fill:none;}.cls-2{stroke:#568af2;stroke-linecap:round;stroke-linejoin:round;stroke-width:3px;}</style></defs><title>CodeCrumb</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><g id="ico-72"><line class="cls-2" x1="52.5" y1="57.5" x2="67.5" y2="57.5"/><rect class="cls-2" x="4.5" y="15.5" width="45" height="41" rx="6.27"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/></g></g></g></svg>
        </a>
        <a href="{{ url_for('main.editor') }}" class="new-editor"><i class="material-icons">code</i>Editor</a>
      </div>
      <div class="crumb-note">
        {% with messages = get_flashed_messages() %} {% if messages %} {% for
        message in messages %}
        <span>{{ message }}</span>
        {% endfor%} {% endif %} {% endwith %}
      </div>
      <div class="new-cr">

        <div class="user-crumb tab-menu-link">
          {% if current_user.is_authenticated %}
          <div class="user-crumb tab-menu-link" style="margin: 0">
              <a href="" class="navigate tab-menu-link"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 48 48" class="preview-explore">
              <title>explore other pages</title>
                <path d="M24 21.8c-1.21 0-2.2.99-2.2 2.2s.99 2.2 2.2 2.2c1.22 0 2.2-.99 2.2-2.2s-.98-2.2-2.2-2.2zM24 4C12.95 4 4 12.95 4 24c0 11.04 8.95 20 20 20s20-8.96 20-20c0-11.05-8.95-20-20-20zm4.38 24.38L12 36l7.62-16.38L36 12l-7.62 16.38z"/></svg>Explore</a>
              <div class="user-crumb-menu">
                <a href="" class="close-explorer"><svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="#ffffff">
                  <title>Close</title>
                  <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg></a>
                <a href="{{ url_for('oauth.account') }}" class="first">Dashboard</a>
                <a href="{{ url_for('set_crumb.crumbs') }}">Your crumbs</a>
  
                <a href="{{ url_for('set_crumb.save') }}">New Crumb</a>
                <a href="{{ url_for('oauth.logout') }}" class="logout">Logout</a>
              </div>
            </div>
          {% endif %}
        </div>
        <div class="tab-menu-link">
            <img src="{{ image }}" alt="{{ current_user.username }}" class="user-crumb-img" height="35px" width="35px"/>
        </div>
      </div>
    </div> {% if crumbs.total != 0 %}
  <div class="search">
    <form method="POST" action="">
        {{search.hidden_tag()}}
      <label>{{search.byname}}</label>
      {{search.search}}
    </form>
  </div>
  {% else %}
  <div class="search">
    <form>
      <label
        ><input
          type="text"
          class="disabled"
          placeholder="Filter by name"
          disabled
      /></label>
      <button type="submit" class="disabled" disabled>Search</button>
    </form>
  </div>
  {% endif %}
  <div class="container">
    <div class="container__crumb">
      {% if crumbs.total > 0 %} {% for crumb in crumbs.items %}

      <div class="crumbs">
        <div class="name">
          <span>{{ crumb.crumbName }}</span>
        </div>
        <div class="thumbnail">
          <input
            type="hidden"
            class="crumbSrc"
            name="html"
            value="{{ json.dumps(json_response(crumb, True)) }}"
          />

          <iframe
            id="transcend-preview"
            allow="midi; geolocation; microphone; camera; encrypted-media;"
            sandbox="allow-forms allow-scripts allow-same-origin allow-modals allow-popups"
            allowfullscreen=""
            allowpaymentrequest=""
            frameborder="0"
            src=""
            name="CodeCrumb"
          >
          </iframe>
        </div>

        <div class="select-btn">
          <a
            href="{{url_for('set_crumb.codecrumb', author=crumb.author.username, url=crumb.url)}}"
            >Preview</a
          >
          <a href="#" class="">Export</a>
          <a
            href=""
            data-confirm="Are you sure you want to delete this crumb?"
            data-id="{{ crumb.id }}"
            class="del-tag"
            >Delete</a
          >
        </div>
      </div>
      {% endfor %}
      <div class="deletefooter">
        {% if crumbs.total != 0 %} {% for i in crumbs.iter_pages(left_edge=1,
        right_edge=1, left_current=1, right_current=2) %} {% if i %} {% if
        crumbs.page == i%}
        <div class="del-del">
          <a href="{{url_for('set_crumb.crumbs', page=i)}}" class="form-tag">{{
            i
          }}</a>
        </div>
        {% else %}
        <div class="del-cancel">
          <a href="{{url_for('set_crumb.crumbs', page=i)}}">{{ i }}</a>
        </div>
        {% endif %} {% else %}
        <div class="del-cancel">
          <a href="{{url_for('set_crumb.crumbs', page=i)}}">...</a>
        </div>
        {% endif %} {% endfor %} {% endif %}
      </div>
    </div>
    {% elif crumbs.total == 0 %}
    <div class="empty-crumb">
      <span>Hey {{current_user.username.capitalize()}}, your Crumb is empty!</span>
      <a href="{{ url_for('main.editor') }}" class="add_new"
        >Create a new Crumb ?</a
      >
    </div>

    {% endif %}
  </div>
  <script src="{{url_for('static', filename='js/prepro.js')}}"></script>
  <script src="{{url_for('static', filename='lib/tools/xtern/esprima.js')}}"></script>
  <script src="{{url_for('static', filename='js/app.crumb.js')}}"></script>
  <!-- {% block otherScript %}
  {{ super() }}
  {% endblock %}  -->
  {% endblock %}
</body>

codecrumb/templates/login.html
{% extends 'layout.html' %}
{% block meta %}
<link rel="stylesheet" href="{{url_for('static', filename='css/login.css')}}">
{% endblock %}

<body>
    {% block body %}
    <div class="container">
        <div class="logo">
            <a href="{{url_for('main.editor')}}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 72 72"><defs><style>.cls-1{stroke: none;}.cls-2{fill:none;}.cls-2{stroke:#568af2;stroke-linecap:round;stroke-linejoin:round;stroke-width:3px;}</style></defs><title>CodeCrumb</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><g id="ico-72"><line class="cls-2" x1="52.5" y1="57.5" x2="67.5" y2="57.5"/><rect class="cls-2" x="4.5" y="15.5" width="45" height="41" rx="6.27"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/><polyline class="cls-2" points="21.9 27.38 12.08 37.17 21.9 45.56"/><polyline class="cls-2" points="31.71 27.38 41.53 37.17 31.71 45.56"/><polyline class="cls-2" points="31.66 27.4 23.37 42.95 21.94 45.61"/></g></g></g></svg>
            </a>

        </div>
        <div class="crumb-note">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <span>{{message}}</span>
            {% endfor%}
            {% endif %}
            {% endwith %}

        </div>
        <div class="form-container">

            <div class="login">
                <span class="form-head">Sign In</span>
                <form class="form" action="" method="POST">
                    {{login.hidden_tag()}}

                    <label class="label-outer">{{login.username.label(class="label")}} {{login.username}}</label>
                    {% if login.username.errors %}
                    {% for error in login.username.errors %}
                    <span class="form-error">{{error}}</span>
                    {% endfor %}
                    {% endif %}

                    <label class="label-outer">{{login.password.label(class="label")}} {{login.password}}</label>
                    {% if login.password.errors %}
                    {% for error in login.password.errors %}
                    <span class="form-error">{{error}}</span>
                    {% endfor %}
                    {% endif %}
                    <label type="submit" class="submit">
                        <span></span> <span></span> <span></span> <span></span>
                        {{login.submit(class="submit-btn")}}

                    </label>
                </form>
                <div class="form-util">
                    <a href="{{url_for('oauth.register')}}" class="sign-up-switch">Sign up</a>
                    <a href="#">Reset Password</a>
                </div>
            </div>
        </div>

    </div>

    <!-- <script src="{{url_for('static', filename='js/login.js')}}"></script> -->
    {% endblock %}
</body>

codecrumb/templates/readme.html
{% extends 'layout.html' %} {% block meta%}

<link
  rel="stylesheet"
  href="{{url_for('static', filename='lib/codemirror/lib/vendor.css')}}"
/>
<link
  rel="stylesheet"
  href="{{url_for('static', filename='lib/codemirror/theme/theme.css')}}"
/>
<link
  rel="stylesheet"
  href="{{url_for('static', filename='css/readME.css')}}"
/>

{% endblock %} {% block body %}
<div class="pseudocode-container">
  <header>
    <div class="pseudo-name">Pseudocode: <span class="crumb-name"></span></div>
    <div class="pseudo-toggle">
      <button class="raw-toggler active">Raw</button>
      <button class="compiled-toggler">Compiled</button>
    </div>
  </header>

  <section class="pseudocode">
    <main class="section-main">
      <div class="raw-wrapper show-editor">
        <textarea name="" id="raw" class=""></textarea>
      </div>
      <div class="compiled-wrapper"><textarea id="compiled"></textarea></div>
    </main>
    <section class="demo">
      <div class="demo-header">
        <span>Demo</span>
        <span data-cl="Close demo" class="close-demo">&times;</span>
      </div>
      <div class="demo-body"><textarea name="" id="demo"></textarea></div>
    </section>
    <input type="hidden" name="pseudo" value="{{ toJson }}" id="pseudo-data" />
  </section>
</div>

<script src="{{url_for('static', filename='lib/codemirror/lib/readme-editor-min.js')}}"></script>

<script src="{{url_for('static', filename='js/readMe.js')}}"></script>
{% endblock %}